// Copyright (c) 2026 LNXSeus. All Rights Reserved.
//
// Template for relay_config.h. Copy to relay_config.h (which is .gitignored)
// and fill in the real values. The actual relay_config.h is NEVER committed.
//
// The relay IP is hidden from logs, UI, and settings.json by design. It still
// appears in the compiled binary (strings <exe> will reveal it) - full
// concealment requires DNS, which this build deliberately avoids.

#ifndef RELAY_CONFIG_H
#define RELAY_CONFIG_H

// Relay server host (RackNerd VPS).
#define RELAY_HOST "0.0.0.0"

// Relay server TLS port.
#define RELAY_PORT 5842

// SHA-256 fingerprint of the relay's self-signed certificate, as 32 hex pairs
// separated by colons. Generated by relay/gen_cert.sh:
//   openssl x509 -in cert.pem -noout -fingerprint -sha256
//
// Rotation: when the relay cert changes, update this constant, ship a release,
// THEN swap the cert on the server. See relay/gen_cert.sh for the full procedure.
#define RELAY_CERT_FINGERPRINT_SHA256 \
    "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:" \
    "00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00"

#endif // RELAY_CONFIG_H